<?php

namespace Eventix\PubSub;

use Nats\Connection;
use Nats\ConnectionOptions;

/**
 * Class PubSub
 * @package App\Facades
 *
 * Handle connection to a PubSub implementation, currently only NATS is used, extend this to some generic implementation
 * to make use of different systems (like kafka)
 */
class PubSub {

    /** @var \Nats\Connection  */
    private $client = null;

    // Setup the connection to nats
    public function __construct() {
        if (!env('PUBSUB_ENABLED', false))
            return;

        $this->client = new Connection(
            (new ConnectionOptions())
                ->setHost(env('NATS_HOST', "127.0.0.1"))
                ->setPort(env('NATS_PORT', 4222)));

        try {
            $this->client->connect();
        } catch (\Exception $e) {
            $this->client = null;

            \Log::error("Could not connect to NATS", $e);
        }
    }

    // Close the connection to nats when we exit
    public function __destruct() {
        if (is_null($this->client))
            return;

        $this->client->close();
    }

    /**
     * Send a request to NATS to do something, returns the response
     *
     * @param String $subj The subject (request name) we are doing
     * @param String $data The data which will be sent
     * @return String The response generated by the request handler
     */
    public function request(String $subj, String $data = "") : String {
        if (is_null($this->client))
            abort(500, "errors.pubsub_not_accessible");

        $msg = null;
        $this->client->request($subj, $data, function ($message) use (&$msg) {
            $msg = $message->getBody();
        });

        return $msg;
    }

    /**
     * Send a request to NATS to do something, sends callback to handle the response
     *
     * @param String $subj The subject (request name) we are doing
     * @param String $data The data which will be sent
     * @return String The response generated by the request handler
     */
    public function requestCallback(String $subj, \Closure $cb) {
        if (is_null($this->client))
            abort(500, "errors.pubsub_not_accessible");

        $msg = null;
        $this->client->request($subj, $data, $cb);

        return $msg;
    }

    /**
     * Publish a message over NATS
     *
     * @param String $subj The subject of the message
     * @param String $data The data which will be sent
     */
    public function publish(String $subj, String $data = null) {
        if (is_null($this->client))
            return;

        try {
            return $this->client->publish($subj, $data);
        } catch (\Exception $e) {
            \Log::error("Something went wrong submitting data to NATS", $e);
            abort(500, "errors.pubsub_publish_failed");
        }
    }

    /**
     * @param String $subj The subject to subscribe to
     * @param \Closure $cb The callback which handles a message
     * @return String The string of the identifier of the subscription
     */
    public function subscribe(String $subj, \Closure $cb) : String {
        if (is_null($this->client))
            abort(500, "errors.pubsub_not_accessible");

        return $this->client->subscribe($subj, $cb);
    }
}
